"""add_missing_user_fields

Revision ID: 053765c1e5b0
Revises: 6bcff6a5c8e5
Create Date: 2025-09-10 00:27:15.059266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '053765c1e5b0'
down_revision = '6bcff6a5c8e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verification_expires')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)

    # ### end Alembic commands ###
