"""Add token blacklist table

Revision ID: 0b9bfbacf32b
Revises: 2609520fe8b3
Create Date: 2025-09-11 20:48:20.619574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9bfbacf32b'
down_revision = '2609520fe8b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_blacklisted_at'), ['blacklisted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blacklist_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_token_blacklist_expires_at', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blacklist_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_blacklist_token_jti'), ['token_jti'], unique=True)
        batch_op.create_index('ix_token_blacklist_user_blacklisted', ['user_id', 'blacklisted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blacklist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_user_id'))
        batch_op.drop_index('ix_token_blacklist_user_blacklisted')
        batch_op.drop_index(batch_op.f('ix_token_blacklist_token_jti'))
        batch_op.drop_index(batch_op.f('ix_token_blacklist_id'))
        batch_op.drop_index('ix_token_blacklist_expires_at')
        batch_op.drop_index(batch_op.f('ix_token_blacklist_created_at'))
        batch_op.drop_index(batch_op.f('ix_token_blacklist_blacklisted_at'))

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
