"""add_password_reset_fields

Revision ID: 2609520fe8b3
Revises: 3200e83c8ec5
Create Date: 2025-09-10 16:44:05.603521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2609520fe8b3'
down_revision = '3200e83c8ec5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
