"""Enhanced chat models for advanced thread and message management

Revision ID: 5615e4ee311c
Revises: c0f7e5bf7d0d
Create Date: 2025-09-23 21:13:31.234504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5615e4ee311c'
down_revision = 'c0f7e5bf7d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('start_position', sa.BigInteger(), nullable=False),
    sa.Column('end_position', sa.BigInteger(), nullable=False),
    sa.Column('page_number', sa.BigInteger(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('vector_store_id', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.BigInteger(), nullable=False),
    sa.Column('character_count', sa.BigInteger(), nullable=False),
    sa.Column('word_count', sa.BigInteger(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['chat_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_document_chunks_document', ['document_id'], unique=False)
        batch_op.create_index('idx_document_chunks_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_document_chunks_index', ['chunk_index'], unique=False)
        batch_op.create_index('idx_document_chunks_page', ['page_number'], unique=False)
        batch_op.create_index('idx_document_chunks_vector_store', ['vector_store_id'], unique=False)

    with op.batch_alter_table('chat_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_extension', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('checksum', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('virus_scan_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('virus_scan_result', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processing_attempts', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_metadata', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('content_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('character_count', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('chunk_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('embedding_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vector_store_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('access_permissions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('sharing_settings', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('storage_provider', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('backup_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('download_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('view_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('search_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processing_metadata', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('analysis_results', sa.JSON(), nullable=False))
        batch_op.create_index('idx_chat_documents_created', ['created_at'], unique=False)
        batch_op.create_index('idx_chat_documents_embedding', ['embedding_status'], unique=False)
        batch_op.create_index('idx_chat_documents_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_chat_documents_status', ['processing_status'], unique=False)
        batch_op.create_index('idx_chat_documents_thread', ['thread_id'], unique=False)
        batch_op.create_index('idx_chat_documents_type', ['document_type'], unique=False)
        batch_op.create_index('idx_chat_documents_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint(None, ['content_hash'])
        batch_op.drop_column('content')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('original_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('version', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('ai_request_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tokens_used', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('processing_time_ms', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('parent_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('content_summary', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('content_vector', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_metadata', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('annotations', sa.JSON(), nullable=False))
        batch_op.create_index('idx_chat_messages_ai_request', ['ai_request_id'], unique=False)
        batch_op.create_index('idx_chat_messages_parent', ['parent_message_id'], unique=False)
        batch_op.create_index('idx_chat_messages_status', ['status'], unique=False)
        batch_op.create_index('idx_chat_messages_thread_created', ['thread_id', 'created_at'], unique=False)
        batch_op.create_index('idx_chat_messages_type_role', ['message_type', 'role'], unique=False)
        batch_op.create_index('idx_chat_messages_user_thread', ['user_id', 'thread_id'], unique=False)
        batch_op.create_foreign_key(None, 'chat_messages', ['parent_message_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_messages', ['reply_to_message_id'], ['id'])

    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('parent_thread_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thread_order', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('sharing_permissions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('access_level', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('message_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('document_count', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('total_tokens_used', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('ai_configuration', sa.JSON(), nullable=False))
        batch_op.create_index('idx_chat_threads_category', ['category'], unique=False)
        batch_op.create_index('idx_chat_threads_hierarchy', ['parent_thread_id', 'thread_order'], unique=False)
        batch_op.create_index('idx_chat_threads_last_message', ['last_message_at'], unique=False)
        batch_op.create_index('idx_chat_threads_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_chat_threads_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_foreign_key(None, 'chat_threads', ['parent_thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_chat_threads_user_status')
        batch_op.drop_index('idx_chat_threads_updated_at')
        batch_op.drop_index('idx_chat_threads_last_message')
        batch_op.drop_index('idx_chat_threads_hierarchy')
        batch_op.drop_index('idx_chat_threads_category')
        batch_op.drop_column('ai_configuration')
        batch_op.drop_column('total_tokens_used')
        batch_op.drop_column('document_count')
        batch_op.drop_column('message_count')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('last_message_at')
        batch_op.drop_column('access_level')
        batch_op.drop_column('sharing_permissions')
        batch_op.drop_column('thread_order')
        batch_op.drop_column('parent_thread_id')
        batch_op.drop_column('is_shared')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')
        batch_op.drop_column('status')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_chat_messages_user_thread')
        batch_op.drop_index('idx_chat_messages_type_role')
        batch_op.drop_index('idx_chat_messages_thread_created')
        batch_op.drop_index('idx_chat_messages_status')
        batch_op.drop_index('idx_chat_messages_parent')
        batch_op.drop_index('idx_chat_messages_ai_request')
        batch_op.drop_column('annotations')
        batch_op.drop_column('ai_metadata')
        batch_op.drop_column('content_vector')
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('content_summary')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('reply_to_message_id')
        batch_op.drop_column('parent_message_id')
        batch_op.drop_column('processing_time_ms')
        batch_op.drop_column('tokens_used')
        batch_op.drop_column('ai_provider')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_request_id')
        batch_op.drop_column('version')
        batch_op.drop_column('edit_count')
        batch_op.drop_column('original_content')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('chat_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_chat_documents_user')
        batch_op.drop_index('idx_chat_documents_type')
        batch_op.drop_index('idx_chat_documents_thread')
        batch_op.drop_index('idx_chat_documents_status')
        batch_op.drop_index('idx_chat_documents_hash')
        batch_op.drop_index('idx_chat_documents_embedding')
        batch_op.drop_index('idx_chat_documents_created')
        batch_op.drop_column('analysis_results')
        batch_op.drop_column('processing_metadata')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('search_count')
        batch_op.drop_column('view_count')
        batch_op.drop_column('download_count')
        batch_op.drop_column('backup_status')
        batch_op.drop_column('storage_provider')
        batch_op.drop_column('storage_path')
        batch_op.drop_column('sharing_settings')
        batch_op.drop_column('access_permissions')
        batch_op.drop_column('is_public')
        batch_op.drop_column('vector_store_id')
        batch_op.drop_column('embedding_status')
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('chunk_count')
        batch_op.drop_column('character_count')
        batch_op.drop_column('word_count')
        batch_op.drop_column('page_count')
        batch_op.drop_column('content_summary')
        batch_op.drop_column('extracted_metadata')
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('processing_completed_at')
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('processing_attempts')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('virus_scan_result')
        batch_op.drop_column('virus_scan_status')
        batch_op.drop_column('checksum')
        batch_op.drop_column('file_extension')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_document_chunks_vector_store')
        batch_op.drop_index('idx_document_chunks_page')
        batch_op.drop_index('idx_document_chunks_index')
        batch_op.drop_index('idx_document_chunks_hash')
        batch_op.drop_index('idx_document_chunks_document')

    op.drop_table('document_chunks')
    # ### end Alembic commands ###
