"""add_image_generation_tables

Revision ID: 600644171768
Revises: fc78da45f18c
Create Date: 2025-09-30 01:34:15.018266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600644171768'
down_revision = 'fc78da45f18c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
