"""fix_image_foreign_keys

Revision ID: 6b400376be29
Revises: 7099470db1a4
Create Date: 2025-10-04 19:00:07.053460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b400376be29'
down_revision = '7099470db1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('generated_images_message_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('generated_images_thread_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_messages', ['message_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'chat_threads', ['thread_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('generated_images_thread_id_fkey'), 'chat_threads', ['thread_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('generated_images_message_id_fkey'), 'chat_messages', ['message_id'], ['id'])

    # ### end Alembic commands ###
