"""add_email_verification_fields

Revision ID: 6bcff6a5c8e5
Revises: d60c24761b24
Create Date: 2025-09-09 23:20:56.645802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcff6a5c8e5'
down_revision = 'd60c24761b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_column('email_verification_expires')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
