"""Add chat system tables

Revision ID: c0f7e5bf7d0d
Revises: 8287f2a893f9
Create Date: 2025-09-23 10:58:30.284816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0f7e5bf7d0d'
down_revision = '8287f2a893f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_users_auth_method'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('role')
        batch_op.drop_column('last_logout')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_logout', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_auth_method'), ['auth_method'], unique=False)
        batch_op.alter_column('auth_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'PASSWORD'::character varying"),
               existing_nullable=False)

    # ### end Alembic commands ###
