name: Docker Compose Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  docker-compose-validation:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate docker-compose configuration
        run: |
          docker-compose config --quiet
      
      - name: Pull Docker images
        run: |
          docker-compose pull
      
      - name: Test container startup
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
      
      - name: Check service health
        run: |
          docker-compose ps | grep "Up" || exit 1
      
      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v
